image: node:12.17.0.

pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cl@15.2.8
    - npm install
    - ng build
    - mkdir -p public
    - mv dist/barber-app/* public
  artifacts:
    paths:
      - public